window.esdocSearchIndex = [
  [
    "@edit-distance/myers-1986/src/recursedeeper.js~recursedeeper",
    "class/src/RecurseDeeper.js~RecurseDeeper.html",
    "<span>RecurseDeeper</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/RecurseDeeper.js</span>",
    "class"
  ],
  [
    "@edit-distance/myers-1986/src/split.js~split",
    "function/index.html#static-function-Split",
    "<span>Split</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/Split.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/stackentry.js~stackentry",
    "function/index.html#static-function-StackEntry",
    "<span>StackEntry</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/StackEntry.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/arrayalloc.js~arrayalloc",
    "function/index.html#static-function-arrayAlloc",
    "<span>arrayAlloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/arrayAlloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/arrayrealloc.js~arrayrealloc",
    "function/index.html#static-function-arrayRealloc",
    "<span>arrayRealloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/arrayRealloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/arraytype.js~arraytype",
    "function/index.html#static-function-arrayType",
    "<span>arrayType</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/arrayType.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/backwardextend.js~backwardextend",
    "function/index.html#static-function-backwardExtend",
    "<span>backwardExtend</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/backwardExtend.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/backwardstep.js~backwardstep",
    "function/index.html#static-function-backwardStep",
    "<span>backwardStep</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/backwardStep.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/boundalloc.js~boundalloc",
    "function/index.html#static-function-boundAlloc",
    "<span>boundAlloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/boundAlloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/diff32.js~diff32",
    "function/index.html#static-function-diff32",
    "<span>diff32</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/diff32.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/diff.js~diff",
    "function/index.html#static-function-diff",
    "<span>diff</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/diff.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/forwardextend.js~forwardextend",
    "function/index.html#static-function-forwardExtend",
    "<span>forwardExtend</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/forwardExtend.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/forwardstep.js~forwardstep",
    "function/index.html#static-function-forwardStep",
    "<span>forwardStep</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/forwardStep.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/lbound.js~lbound",
    "function/index.html#static-function-lBound",
    "<span>lBound</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/lBound.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/longestcommonprefix.js~longestcommonprefix",
    "function/index.html#static-function-longestCommonPrefix",
    "<span>longestCommonPrefix</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/longestCommonPrefix.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/longestcommonsuffix.js~longestcommonsuffix",
    "function/index.html#static-function-longestCommonSuffix",
    "<span>longestCommonSuffix</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/longestCommonSuffix.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/makescan.js~makescan",
    "function/index.html#static-function-makeScan",
    "<span>makeScan</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/makeScan.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/oneway.js~oneway",
    "function/index.html#static-function-oneWay",
    "<span>oneWay</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/oneWay.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/onewayalloc.js~onewayalloc",
    "function/index.html#static-function-oneWayAlloc",
    "<span>oneWayAlloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/oneWayAlloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/recurse.js~recurse",
    "function/index.html#static-function-recurse",
    "<span>recurse</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/recurse.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/recursedeep.js~recursedeep",
    "function/index.html#static-function-recurseDeep",
    "<span>recurseDeep</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/recurseDeep.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/recursedeeperstep.js~recursedeeperstep",
    "function/index.html#static-function-recurseDeeperStep",
    "<span>recurseDeeperStep</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/recurseDeeperStep.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/twoway.js~twoway",
    "function/index.html#static-function-twoWay",
    "<span>twoWay</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/twoWay.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/twowayalloc.js~twowayalloc",
    "function/index.html#static-function-twoWayAlloc",
    "<span>twoWayAlloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/twoWayAlloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/twowayrealloc.js~twowayrealloc",
    "function/index.html#static-function-twoWayRealloc",
    "<span>twoWayRealloc</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/twoWayRealloc.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/twowayscan.js~twowayscan",
    "function/index.html#static-function-twoWayScan",
    "<span>twoWayScan</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/twoWayScan.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/ubound.js~ubound",
    "function/index.html#static-function-uBound",
    "<span>uBound</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/uBound.js</span>",
    "function"
  ],
  [
    "@edit-distance/myers-1986/src/validate32.js~validate32",
    "function/index.html#static-function-validate32",
    "<span>validate32</span> <span class=\"search-result-import-path\">@edit-distance/myers-1986/src/validate32.js</span>",
    "function"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/recursedeeper.js",
    "file/src/RecurseDeeper.js.html",
    "src/RecurseDeeper.js",
    "file"
  ],
  [
    "src/recursedeeper.js~recursedeeper#b",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-member-B",
    "src/RecurseDeeper.js~RecurseDeeper#B",
    "member"
  ],
  [
    "src/recursedeeper.js~recursedeeper#[symbol.iterator]",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-method-[Symbol.iterator]",
    "src/RecurseDeeper.js~RecurseDeeper#[Symbol.iterator]",
    "method"
  ],
  [
    "src/recursedeeper.js~recursedeeper#_eq",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-member-_eq",
    "src/RecurseDeeper.js~RecurseDeeper#_eq",
    "member"
  ],
  [
    "src/recursedeeper.js~recursedeeper#_stack",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-member-_stack",
    "src/RecurseDeeper.js~RecurseDeeper#_stack",
    "member"
  ],
  [
    "src/recursedeeper.js~recursedeeper#constructor",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-constructor-constructor",
    "src/RecurseDeeper.js~RecurseDeeper#constructor",
    "method"
  ],
  [
    "src/recursedeeper.js~recursedeeper#next",
    "class/src/RecurseDeeper.js~RecurseDeeper.html#instance-method-next",
    "src/RecurseDeeper.js~RecurseDeeper#next",
    "method"
  ],
  [
    "src/split.js",
    "file/src/Split.js.html",
    "src/Split.js",
    "file"
  ],
  [
    "src/stackentry.js",
    "file/src/StackEntry.js.html",
    "src/StackEntry.js",
    "file"
  ],
  [
    "src/arrayalloc.js",
    "file/src/arrayAlloc.js.html",
    "src/arrayAlloc.js",
    "file"
  ],
  [
    "src/arrayrealloc.js",
    "file/src/arrayRealloc.js.html",
    "src/arrayRealloc.js",
    "file"
  ],
  [
    "src/arraytype.js",
    "file/src/arrayType.js.html",
    "src/arrayType.js",
    "file"
  ],
  [
    "src/backwardextend.js",
    "file/src/backwardExtend.js.html",
    "src/backwardExtend.js",
    "file"
  ],
  [
    "src/backwardstep.js",
    "file/src/backwardStep.js.html",
    "src/backwardStep.js",
    "file"
  ],
  [
    "src/boundalloc.js",
    "file/src/boundAlloc.js.html",
    "src/boundAlloc.js",
    "file"
  ],
  [
    "src/diff.js",
    "file/src/diff.js.html",
    "src/diff.js",
    "file"
  ],
  [
    "src/diff32.js",
    "file/src/diff32.js.html",
    "src/diff32.js",
    "file"
  ],
  [
    "src/forwardextend.js",
    "file/src/forwardExtend.js.html",
    "src/forwardExtend.js",
    "file"
  ],
  [
    "src/forwardstep.js",
    "file/src/forwardStep.js.html",
    "src/forwardStep.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/lbound.js",
    "file/src/lBound.js.html",
    "src/lBound.js",
    "file"
  ],
  [
    "src/longestcommonprefix.js",
    "file/src/longestCommonPrefix.js.html",
    "src/longestCommonPrefix.js",
    "file"
  ],
  [
    "src/longestcommonsuffix.js",
    "file/src/longestCommonSuffix.js.html",
    "src/longestCommonSuffix.js",
    "file"
  ],
  [
    "src/makescan.js",
    "file/src/makeScan.js.html",
    "src/makeScan.js",
    "file"
  ],
  [
    "src/oneway.js",
    "file/src/oneWay.js.html",
    "src/oneWay.js",
    "file"
  ],
  [
    "src/onewayalloc.js",
    "file/src/oneWayAlloc.js.html",
    "src/oneWayAlloc.js",
    "file"
  ],
  [
    "src/recurse.js",
    "file/src/recurse.js.html",
    "src/recurse.js",
    "file"
  ],
  [
    "src/recursedeep.js",
    "file/src/recurseDeep.js.html",
    "src/recurseDeep.js",
    "file"
  ],
  [
    "src/recursedeeperstep.js",
    "file/src/recurseDeeperStep.js.html",
    "src/recurseDeeperStep.js",
    "file"
  ],
  [
    "src/twoway.js",
    "file/src/twoWay.js.html",
    "src/twoWay.js",
    "file"
  ],
  [
    "src/twowayalloc.js",
    "file/src/twoWayAlloc.js.html",
    "src/twoWayAlloc.js",
    "file"
  ],
  [
    "src/twowayrealloc.js",
    "file/src/twoWayRealloc.js.html",
    "src/twoWayRealloc.js",
    "file"
  ],
  [
    "src/twowayscan.js",
    "file/src/twoWayScan.js.html",
    "src/twoWayScan.js",
    "file"
  ],
  [
    "src/ubound.js",
    "file/src/uBound.js.html",
    "src/uBound.js",
    "file"
  ],
  [
    "src/validate32.js",
    "file/src/validate32.js.html",
    "src/validate32.js",
    "file"
  ]
]